---
- name: Add hummingbird user
  user: 
    name: hummingbird
    createhome: no
    system: yes
- name: Install memcache
  apt:
    name: memcached
    state: present
- name: Configure memcached
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^127\.0\.0\.1'
    line: '-l {{ service_ip }}'
- name: Restart memcached
  service:
    enabled: yes
    name: memcached
    state: restarted
- name: Install curl
  apt:
    name: curl
    state: present
- name: Install jq
  apt:
    name: jq
    state: present
- name: Print downloadtmpdir
  debug:
    var: downloadtmpdir
- name: Copy binary to node
  copy:
    src: "{{downloadtmpdir.path}}/hummingbird"
    dest: /usr/local/bin/hummingbird
    mode: 0755
    force: yes
- name: Create /etc/hummingbird
  file:
    path: /etc/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: Copy /etc/hummingbird/hummingbird.conf
  template:
    src: etc/hummingbird.conf.j2
    dest: /etc/hummingbird/hummingbird.conf
    mode: 0644
    owner: hummingbird
    group: hummingbird
- name: Create /var/cache/swift
  file:
    path: /var/cache/swift
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: Create /var/log/hummingbird
  file:
    path: /var/log/hummingbird
    state: directory
    mode: 0755
    owner: syslog
    group: adm
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
- name: Copy rsyslog config
  copy:
    src: rsyslog.d/20-hbird.conf
    dest: /etc/rsyslog.d/20-hbird.conf
    mode: 0644
- name: Install logrotate
  apt:
    name: logrotate
    state: present
- name: Copy logrotate config
  copy:
    src: logrotate.d/hummingbird
    dest: /etc/logrotate.d/hummingbird
    mode: 0644
- name: Restart rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: restarted
- name: Create /var/run/hummingbird
  file:
    path: /var/run/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: create /srv/hummingbird
  file:
    path: /srv/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
